In [12]:
# Read hdf5 file having the dataset

import numpy as np
import h5py

hf = h5py.File('SVHN_single_grey1.h5', 'r')

print(hf.keys())

<KeysViewHDF5 ['X_test', 'X_train', 'X_val', 'y_test', 'y_train', 'y_val']>


In [13]:
X_train = hf.get('X_train')
trainX = np.array(X_train)
# normalize inputs from 0-255 to 0-1
trainX = trainX / 255.0

trainX.shape

(42000, 32, 32)

In [14]:
y_train = hf.get('y_train')
trainY = np.array(y_train)
trainY.shape

(42000,)

In [15]:
X_test = hf.get('X_test')
testX = np.array(X_test)
# normalize inputs from 0-255 to 0-1
testX = testX / 255.0
testX.shape

(18000, 32, 32)

In [16]:
y_test = hf.get('y_test')
testY = np.array(y_test)
testY.shape

(18000,)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [18]:
# Changing dimensions to N x D = 32x32
# Number of samples you want in training data.
N = 42000
x_tr = []
for i in range(N):
    x_tr.append(trainX[i,:].flatten())
x_te = []
for i in range(18000):
    x_te.append(testX[i,:].flatten())

In [19]:

model = KNeighborsClassifier(n_neighbors = 1)
model.fit(x_tr, trainY)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [ ]:
y_pred = model.predict(x_te)

In [10]:
print(classification_report(testY, y_pred))

              precision    recall  f1-score   support

           0       0.47      0.52      0.49      1814
           1       0.50      0.57      0.53      1828
           2       0.54      0.48      0.51      1803
           3       0.37      0.35      0.36      1719
           4       0.60      0.57      0.59      1812
           5       0.38      0.33      0.36      1768
           6       0.38      0.39      0.39      1832
           7       0.63      0.59      0.61      1808
           8       0.34      0.37      0.36      1812
           9       0.39      0.40      0.40      1804

   micro avg       0.46      0.46      0.46     18000
   macro avg       0.46      0.46      0.46     18000
weighted avg       0.46      0.46      0.46     18000



In [11]:
print ("Confusion matrix")
print(confusion_matrix(testY,y_pred))

Confusion matrix
[[ 935   43   51   64   71   65  185   40  170  190]
 [  51 1034  109  122  123   69   68  119   67   66]
 [  63  135  872  131   82   74   65  168   79  134]
 [  67  166  127  610   88  229   82   80  149  121]
 [  85  195   51   71 1039   55  111   35   98   72]
 [  94  103   71  220   54  588  203   48  205  182]
 [ 225   74   51   72  102  154  711   33  295  115]
 [  65  173  146  100   34   38   48 1071   53   80]
 [ 150   62   59  130   86  153  267   44  675  186]
 [ 238   87   89  115   60  113  115   65  192  730]]
